#!/bin/sh

# Environment variables
export PATH="$HOME/.local/bin:$HOME/.config/bspwm/bin:$PATH"
export XDG_CURRENT_DESKTOP="bspwm"
export GTK_THEME="Flat-Remix-GTK-Red-Darkest-Solid:dark"

# Fix Java applications
export _JAVA_AWT_WM_NONREPARENTING=1

# ╦ ╦╔═╗╦═╗╦╔═╔═╗╔═╗╔═╗╔═╗╔═╗╔═╗
# ║║║║ ║╠╦╝╠╩╗╚═╗╠═╝╠═╣║  ║╣ ╚═╗
# ╚╩╝╚═╝╩╚═╩ ╩╚═╝╩  ╩ ╩╚═╝╚═╝╚═╝

MonitorSetup

# ╔╗ ╔═╗╔═╗╦ ╦╔╦╗  ╔═╗╔═╗╔╗╔╔═╗╦╔═╗
# ╠╩╗╚═╗╠═╝║║║║║║  ║  ║ ║║║║╠╣ ║║ ╦
# ╚═╝╚═╝╩  ╚╩╝╩ ╩  ╚═╝╚═╝╝╚╝╚  ╩╚═╝

bspc config external_rules_command "${HOME}/.config/bspwm/bin/ExternalRules"

bspc config window_gap               12
bspc config split_ratio              0.53
bspc config single_monocle           true

bspc config automatic_scheme         longest_side
bspc config initial_polarity         second_child
bspc config removal_adjustment       true

bspc config focus_follows_pointer    true
bspc config pointer_follows_focus    false
bspc config pointer_follows_monitor  true
bspc config pointer_motion_interval  20
bspc config pointer_modifier         mod4
bspc config pointer_action1          move
bspc config pointer_action2          resize_side
bspc config pointer_action3          resize_corner

# ╔═╗╦ ╦╔╦╗╔═╗╔═╗╔╦╗╔═╗╦═╗╔╦╗
# ╠═╣║ ║ ║ ║ ║╚═╗ ║ ╠═╣╠╦╝ ║
# ╩ ╩╚═╝ ╩ ╚═╝╚═╝ ╩ ╩ ╩╩╚═ ╩

run() {
    if ! pidof -q "$1"; then
        "$@" &
    fi
}

# Set system vars for polybar
"${HOME}/.config/bspwm/bin/SetSysVars"

# Launch sxhkd
run sxhkd -c "${HOME}/.config/bspwm/config/sxhkdrc"

# Load theme
"${HOME}/.config/bspwm/bin/Theme.sh"

# Launch compositor
run picom --config "${HOME}/.config/bspwm/config/picom.conf"

# Launch xsettingsd
run xsettingsd --config="${HOME}/.config/bspwm/config/xsettingsd"

# Launch eww
pidof -q eww || eww -c "${HOME}/.config/bspwm/eww" daemon &

# Clipboard daemon
run clipcatd

# Polkit agent
run lxpolkit

# First run message
if [ ! -f "$HOME/.config/bspwm/config/.first_run_done" ]; then
    alacritty --hold -e sh -c \
    'cat "$HOME/.config/bspwm/config/FirstMessage.txt"; sleep 0.1'
    
    touch "$HOME/.config/bspwm/config/.first_run_done"
fi

# Low battery alert
"${HOME}/.config/bspwm/bin/batterylevel.sh" &
