[dmenu]
# Forzamos el estilo Blood Neon: fondo negro profundo y bordes rojos
# 'bw' es el ancho del borde, 'lines' la cantidad de redes a mostrar
dmenu_command = rofi -dmenu -i -location 0 -p " " -theme-str 'window {width: 450px; border: 3px; border-color: #b80707; background-color: #0a0000;} listview {lines: 12; scrollbar: false;} element selected {background-color: #b80707; text-color: #ffffff;}'

# Caracteres de estado
active_chars = 󰄬
highlight = True
compact = False

[dmenu_passphrase]
# Seguridad: que no se vea lo que escribís en bspwm
obscure = True
obscure_char = *

[symbols]
# Iconos de seguridad (Aparecerán junto al nombre de la red)
auth = 
wired = 󰈀

# Iconos de intensidad con Nerd Fonts (estilo arco)
nm_1 = 󰤯
nm_2 = 󰤟
nm_3 = 󰤢
nm_4 = 󰤥
nm_5 = 󰤨
